import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// CPE requirements by state - compiled from NASBA Registry and state board websites
// Sources: nasbaregistry.org, state board of accountancy websites
// Last verified: December 2024

interface StateRuleData {
  stateCode: string
  stateName: string
  boardName: string
  boardUrl: string
  cycleType: 'CALENDAR_YEAR' | 'ROLLING' | 'ANNIVERSARY' | 'FISCAL_YEAR' | 'BIENNIAL_EVEN' | 'BIENNIAL_ODD'
  cycleLengthYears: number
  totalHoursRequired: number
  ethicsHoursRequired: number
  minLiveHours: number
  subjectMinimums: Record<string, number> | null
  carryoverAllowed: boolean
  maxCarryoverHours: number | null
  specialRules: string | null
  sourceUrls: string[]
}

const stateRules: StateRuleData[] = [
  {
    stateCode: 'AL',
    stateName: 'Alabama',
    boardName: 'Alabama State Board of Public Accountancy',
    boardUrl: 'https://www.asbpa.alabama.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 8 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Nano learning limited to 25% of total hours',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/alabama'],
  },
  {
    stateCode: 'AK',
    stateName: 'Alaska',
    boardName: 'Alaska State Board of Public Accountancy',
    boardUrl: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/BoardofPublicAccountancy.aspx',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Minimum 20 hours per year. Micro-learning under 1 hour capped at 10 hours.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/alaska'],
  },
  {
    stateCode: 'AZ',
    stateName: 'Arizona',
    boardName: 'Arizona State Board of Accountancy',
    boardUrl: 'https://azaccountancy.gov/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 16,
    subjectMinimums: { 'technical': 40 },
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: '40 hours in accounting/auditing/tax/management services. 16 hours classroom minimum.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/arizona'],
  },
  {
    stateCode: 'AR',
    stateName: 'Arkansas',
    boardName: 'Arkansas State Board of Public Accountancy',
    boardUrl: 'https://www.arkansas.gov/asbpa/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 4,
    minLiveHours: 8,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Group study minimum 8 hours. Three-year look-back provision.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/arkansas'],
  },
  {
    stateCode: 'CA',
    stateName: 'California',
    boardName: 'California Board of Accountancy',
    boardUrl: 'https://www.dca.ca.gov/cba/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'technical': 40, 'fraud': 4, 'regulatory_review': 2 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: '20-hour yearly minimum. 12 hours yearly minimum in technical subjects. 2-hour regulatory review required every 6 years.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/california'],
  },
  {
    stateCode: 'CO',
    stateName: 'Colorado',
    boardName: 'Colorado State Board of Accountancy',
    boardUrl: 'https://dpo.colorado.gov/Accountancy',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 40,
    specialRules: 'Personal development limited to 20%. 2 hours may be in Colorado Rules and Regulations.',
    sourceUrls: ['https://dpo.colorado.gov/Accountancy/CPE'],
  },
  {
    stateCode: 'CT',
    stateName: 'Connecticut',
    boardName: 'Connecticut State Board of Accountancy',
    boardUrl: 'https://portal.ct.gov/DCP/License-Services-Division/All-License-Applications/Certified-Public-Accountant',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'attest_compilation': 8 },
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: '8 hours in attest/compilation services for those providing such services.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/connecticut'],
  },
  {
    stateCode: 'DE',
    stateName: 'Delaware',
    boardName: 'Delaware Board of Accountancy',
    boardUrl: 'https://dpr.delaware.gov/boards/accountancy/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 8, 'taxation': 8 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Delaware-specific ethics required.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/delaware'],
  },
  {
    stateCode: 'DC',
    stateName: 'Washington D.C.',
    boardName: 'DC Board of Accountancy',
    boardUrl: 'https://dcra.dc.gov/page/board-accountancy',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Courses must be from NASBA Registry, QAS-approved, or exempt organizations.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/district-of-columbia'],
  },
  {
    stateCode: 'FL',
    stateName: 'Florida',
    boardName: 'Florida Board of Accountancy',
    boardUrl: 'https://www.myfloridalicense.com/DBPR/certified-public-accounting/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 8 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'No more than 20 hours in behavioral subjects. Ethics must be completed with same provider if split.',
    sourceUrls: ['https://www2.myfloridalicense.com/certified-public-accounting/licensure/continuing-professional-education/'],
  },
  {
    stateCode: 'GA',
    stateName: 'Georgia',
    boardName: 'Georgia State Board of Accountancy',
    boardUrl: 'https://sos.ga.gov/PLB/acct/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'technical': 40 },
    carryoverAllowed: true,
    maxCarryoverHours: 15,
    specialRules: '1 hour Georgia-specific ethics required. Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/georgia'],
  },
  {
    stateCode: 'HI',
    stateName: 'Hawaii',
    boardName: 'Hawaii Board of Public Accountancy',
    boardUrl: 'https://cca.hawaii.gov/pvl/boards/accountancy/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/hawaii'],
  },
  {
    stateCode: 'ID',
    stateName: 'Idaho',
    boardName: 'Idaho State Board of Accountancy',
    boardUrl: 'https://isba.idaho.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Ethics required every 2 years.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/idaho'],
  },
  {
    stateCode: 'IL',
    stateName: 'Illinois',
    boardName: 'Illinois Board of Examiners',
    boardUrl: 'https://www.ilboe.org/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/illinois'],
  },
  {
    stateCode: 'IN',
    stateName: 'Indiana',
    boardName: 'Indiana Board of Accountancy',
    boardUrl: 'https://www.in.gov/pla/professions/indiana-board-of-accountancy/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/indiana'],
  },
  {
    stateCode: 'IA',
    stateName: 'Iowa',
    boardName: 'Iowa Accountancy Examining Board',
    boardUrl: 'https://plb.iowa.gov/board/accountancy-examining-board',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 24 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/iowa'],
  },
  {
    stateCode: 'KS',
    stateName: 'Kansas',
    boardName: 'Kansas Board of Accountancy',
    boardUrl: 'https://ksboa.kansas.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/kansas'],
  },
  {
    stateCode: 'KY',
    stateName: 'Kentucky',
    boardName: 'Kentucky State Board of Accountancy',
    boardUrl: 'https://cpa.ky.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 3,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Ethics can be non-Kentucky specific.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/kentucky'],
  },
  {
    stateCode: 'LA',
    stateName: 'Louisiana',
    boardName: 'Louisiana State Board of CPAs',
    boardUrl: 'https://cpaboard.state.la.us/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: 'Personal development limited to 20 hours.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/louisiana'],
  },
  {
    stateCode: 'ME',
    stateName: 'Maine',
    boardName: 'Maine Board of Accountancy',
    boardUrl: 'https://www.maine.gov/pfr/professionallicensing/professions/accountancy',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/maine'],
  },
  {
    stateCode: 'MD',
    stateName: 'Maryland',
    boardName: 'Maryland State Board of Public Accountancy',
    boardUrl: 'https://www.dllr.state.md.us/license/cpa/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/maryland'],
  },
  {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    boardName: 'Massachusetts Board of Public Accountancy',
    boardUrl: 'https://www.mass.gov/orgs/board-of-registration-of-public-accountancy',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/massachusetts'],
  },
  {
    stateCode: 'MI',
    stateName: 'Michigan',
    boardName: 'Michigan Board of Accountancy',
    boardUrl: 'https://www.michigan.gov/lara/bureau-list/bpl/occ/prof/accountancy',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/michigan'],
  },
  {
    stateCode: 'MN',
    stateName: 'Minnesota',
    boardName: 'Minnesota Board of Accountancy',
    boardUrl: 'https://boa.state.mn.us/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/minnesota'],
  },
  {
    stateCode: 'MS',
    stateName: 'Mississippi',
    boardName: 'Mississippi State Board of Public Accountancy',
    boardUrl: 'https://www.msbpa.ms.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/mississippi'],
  },
  {
    stateCode: 'MO',
    stateName: 'Missouri',
    boardName: 'Missouri State Board of Accountancy',
    boardUrl: 'https://pr.mo.gov/accountancy.asp',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 40,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/missouri'],
  },
  {
    stateCode: 'MT',
    stateName: 'Montana',
    boardName: 'Montana Board of Public Accountants',
    boardUrl: 'https://boards.bsd.dli.mt.gov/public-accountants',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 3,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/montana'],
  },
  {
    stateCode: 'NE',
    stateName: 'Nebraska',
    boardName: 'Nebraska State Board of Public Accountancy',
    boardUrl: 'https://nbpa.nebraska.gov/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 40,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/nebraska'],
  },
  {
    stateCode: 'NV',
    stateName: 'Nevada',
    boardName: 'Nevada State Board of Accountancy',
    boardUrl: 'https://www.nvaccountancy.com/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/nevada'],
  },
  {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    boardName: 'New Hampshire Board of Accountancy',
    boardUrl: 'https://www.oplc.nh.gov/board-accountancy',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/new-hampshire'],
  },
  {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    boardName: 'New Jersey State Board of Accountancy',
    boardUrl: 'https://www.njconsumeraffairs.gov/acc/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 24 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: '24 A&A hours for those in public practice. 4 hours NJ Law & Ethics.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/new-jersey'],
  },
  {
    stateCode: 'NM',
    stateName: 'New Mexico',
    boardName: 'New Mexico Board of Accountancy',
    boardUrl: 'https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/accountancy-board/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/new-mexico'],
  },
  {
    stateCode: 'NY',
    stateName: 'New York',
    boardName: 'New York State Board for Public Accountancy',
    boardUrl: 'http://www.op.nysed.gov/prof/cpa/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 40,
    specialRules: 'Ethics course must be from a NY State registered CPE ethics provider.',
    sourceUrls: ['https://www.mypescpe.com/newyork-cpe-requirements'],
  },
  {
    stateCode: 'NC',
    stateName: 'North Carolina',
    boardName: 'North Carolina State Board of CPA Examiners',
    boardUrl: 'https://www.nccpaboard.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/north-carolina'],
  },
  {
    stateCode: 'ND',
    stateName: 'North Dakota',
    boardName: 'North Dakota State Board of Accountancy',
    boardUrl: 'https://www.ndsba.nd.gov/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 6,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/north-dakota'],
  },
  {
    stateCode: 'OH',
    stateName: 'Ohio',
    boardName: 'Accountancy Board of Ohio',
    boardUrl: 'https://acc.ohio.gov/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 3,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year. Ohio-specific ethics required.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/ohio'],
  },
  {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    boardName: 'Oklahoma Accountancy Board',
    boardUrl: 'https://www.ok.gov/oab/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/oklahoma'],
  },
  {
    stateCode: 'OR',
    stateName: 'Oregon',
    boardName: 'Oregon Board of Accountancy',
    boardUrl: 'https://www.oregon.gov/boa/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 24,
    specialRules: 'Minimum 24 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/oregon'],
  },
  {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    boardName: 'Pennsylvania State Board of Accountancy',
    boardUrl: 'https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Accountancy/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 24 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: '24 A&A hours if providing attest services.',
    sourceUrls: ['https://www.picpa.org/professional-resources/licensing/cpe-requirements'],
  },
  {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    boardName: 'Rhode Island Board of Accountancy',
    boardUrl: 'https://dbr.ri.gov/divisions/accountancy/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/rhode-island'],
  },
  {
    stateCode: 'SC',
    stateName: 'South Carolina',
    boardName: 'South Carolina Board of Accountancy',
    boardUrl: 'https://llr.sc.gov/acct/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/south-carolina'],
  },
  {
    stateCode: 'SD',
    stateName: 'South Dakota',
    boardName: 'South Dakota Board of Accountancy',
    boardUrl: 'https://dlr.sd.gov/accountancy/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/south-dakota'],
  },
  {
    stateCode: 'TN',
    stateName: 'Tennessee',
    boardName: 'Tennessee State Board of Accountancy',
    boardUrl: 'https://www.tn.gov/commerce/regboards/accountancy.html',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/tennessee'],
  },
  {
    stateCode: 'TX',
    stateName: 'Texas',
    boardName: 'Texas State Board of Public Accountancy',
    boardUrl: 'https://www.tsbpa.texas.gov/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'technical': 60 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Minimum 20 hours per year. Maximum 60 hours from non-technical courses.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/texas'],
  },
  {
    stateCode: 'UT',
    stateName: 'Utah',
    boardName: 'Utah Board of Accountancy',
    boardUrl: 'https://dopl.utah.gov/cpa/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 24,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/utah'],
  },
  {
    stateCode: 'VT',
    stateName: 'Vermont',
    boardName: 'Vermont Board of Public Accountancy',
    boardUrl: 'https://sos.vermont.gov/accountancy/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: { 'accounting_auditing': 8 },
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/vermont'],
  },
  {
    stateCode: 'VA',
    stateName: 'Virginia',
    boardName: 'Virginia Board of Accountancy',
    boardUrl: 'https://www.boa.virginia.gov/',
    cycleType: 'CALENDAR_YEAR',
    cycleLengthYears: 1,
    totalHoursRequired: 40,
    ethicsHoursRequired: 2,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 20,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/virginia'],
  },
  {
    stateCode: 'WA',
    stateName: 'Washington',
    boardName: 'Washington State Board of Accountancy',
    boardUrl: 'https://acb.wa.gov/',
    cycleType: 'ROLLING',
    cycleLengthYears: 3,
    totalHoursRequired: 120,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: false,
    maxCarryoverHours: null,
    specialRules: 'Washington-specific ethics required.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/washington'],
  },
  {
    stateCode: 'WV',
    stateName: 'West Virginia',
    boardName: 'West Virginia Board of Accountancy',
    boardUrl: 'https://www.boa.wv.gov/',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 16,
    specialRules: 'Minimum 16 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/west-virginia'],
  },
  {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    boardName: 'Wisconsin Accounting Examining Board',
    boardUrl: 'https://dsps.wi.gov/pages/Professions/Accountant/Default.aspx',
    cycleType: 'BIENNIAL_EVEN',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 3,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 24,
    specialRules: null,
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/wisconsin'],
  },
  {
    stateCode: 'WY',
    stateName: 'Wyoming',
    boardName: 'Wyoming Board of Certified Public Accountants',
    boardUrl: 'https://cpaboard.wyo.gov/',
    cycleType: 'BIENNIAL_ODD',
    cycleLengthYears: 2,
    totalHoursRequired: 80,
    ethicsHoursRequired: 4,
    minLiveHours: 0,
    subjectMinimums: null,
    carryoverAllowed: true,
    maxCarryoverHours: 24,
    specialRules: 'Minimum 20 hours per year.',
    sourceUrls: ['https://www.nasbaregistry.org/cpe-requirements/wyoming'],
  },
]

async function main() {
  console.log('Seeding state rules...')

  for (const rule of stateRules) {
    await prisma.stateRule.upsert({
      where: { stateCode: rule.stateCode },
      update: {
        stateName: rule.stateName,
        boardName: rule.boardName,
        boardUrl: rule.boardUrl,
        cycleType: rule.cycleType,
        cycleLengthYears: rule.cycleLengthYears,
        totalHoursRequired: rule.totalHoursRequired,
        ethicsHoursRequired: rule.ethicsHoursRequired,
        minLiveHours: rule.minLiveHours,
        subjectMinimums: rule.subjectMinimums ?? undefined,
        carryoverAllowed: rule.carryoverAllowed,
        maxCarryoverHours: rule.maxCarryoverHours,
        specialRules: rule.specialRules,
        sourceUrls: rule.sourceUrls,
        lastVerifiedAt: new Date(),
      },
      create: {
        stateCode: rule.stateCode,
        stateName: rule.stateName,
        boardName: rule.boardName,
        boardUrl: rule.boardUrl,
        cycleType: rule.cycleType,
        cycleLengthYears: rule.cycleLengthYears,
        totalHoursRequired: rule.totalHoursRequired,
        ethicsHoursRequired: rule.ethicsHoursRequired,
        minLiveHours: rule.minLiveHours,
        subjectMinimums: rule.subjectMinimums ?? undefined,
        carryoverAllowed: rule.carryoverAllowed,
        maxCarryoverHours: rule.maxCarryoverHours,
        specialRules: rule.specialRules,
        sourceUrls: rule.sourceUrls,
        lastVerifiedAt: new Date(),
      },
    })
    console.log(`  ${rule.stateCode}: ${rule.stateName}`)
  }

  console.log(`\nSeeded ${stateRules.length} state rules.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
